# Generated by Django 4.0.3 on 2022-05-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gettingstarted', '0002_alter_verification_pancard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='profile',
            field=models.TextField(null=True),
        ),
    ]
