# Generated by Django 4.0.3 on 2022-05-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employed',
            name='add_previous_education',
            field=models.TextField(max_length=50),
        ),
    ]
