# Generated by Django 4.0.3 on 2022-05-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleuser', '0002_alter_employed_add_previous_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration_manage',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employed',
            name='add_previous_education',
            field=models.TextField(),
        ),
    ]
