# Generated by Django 4.0.3 on 2022-05-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleuser', '0003_configuration_manage_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration_manage',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='configuration_manage',
            name='mob_no',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
    ]
