# Generated by Django 4.0.3 on 2022-05-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleuser', '0003_alter_configuration_manage_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college_student',
            name='add_previous_education',
            field=models.CharField(max_length=500),
        ),
    ]
