# Generated by Django 4.0.3 on 2022-05-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleuser', '0004_configuration_manage_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration_manage',
            name='mob_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
